services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: star_burger_prod
      POSTGRES_USER: star_burger_user
      POSTGRES_PASSWORD: Malina96
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U star_burger_user -d star_burger_prod"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: .
    working_dir: /app/backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - backend/star_burger/.env
    environment:
      DJANGO_SETTINGS_MODULE: star_burger.settings
      DATABASE_URL: postgres://star_burger_user:Malina96@db:5432/star_burger_prod
    restart: unless-stopped

  frontend:
    image: node:20
    working_dir: /app/frontend
    command: >
      sh -c "npm install --include=dev && ./node_modules/.bin/parcel build index.js --dist-dir ../bundles --public-url=./ && tail -f /dev/null"
    volumes:
      - ./frontend:/app/frontend
      - ./bundles:/app/bundles
      - node_modules:/app/frontend/node_modules
    ports:
      - "127.0.0.1:1234:1234"
    environment:
      NODE_ENV: production
    restart: unless-stopped

volumes:
  node_modules:
  postgres_data:
